version: 3

tasks:
  proto-build:
    cmd: "protoc --go_out=./pkg/ --go_opt=paths=source_relative --go-grpc_out=./pkg/ --go-grpc_opt=paths=source_relative api/chat/chat.proto"

  build:
    cmd: "go build -o bin/chat ."
